language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - py.test -v --cov-report term-missing --cov=rubberduino -r w tests
after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
